
name: Publish Design System

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semantic version tags (e.g., v1.0.0, v1.2.3)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
      
      - name: Run comprehensive tests
        run: npm run test:coverage
      
      - name: Run legacy tests
        run: npm run test:legacy
      
      - name: Build package
        run: npm run build
      
      - name: Run smoke tests
        run: npm run test:smoke
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Validate package.json version matches git tag
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
          echo "Package version: $PACKAGE_VERSION"
          echo "Tag version: $TAG_VERSION"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: package.json version ($PACKAGE_VERSION) does not match git tag version ($TAG_VERSION)"
            echo "Please update package.json version to match the git tag before publishing"
            exit 1
          fi
          echo "Version validation passed: $PACKAGE_VERSION"
      
      - name: Update package version
        run: npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Trigger downstream projects
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: fanoo2/downstream-project-example
          event-type: design-system-updated
          client-payload: |
            {
              "version": "${{ steps.get_version.outputs.VERSION }}",
              "package": "@fanno/design-system",
              "tag": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "repository": "${{ github.repository }}"
            }
